function showRequests(requests) {
    $("#main").html("");
    let table = $("<table>").addClass("table").attr("id", "requestslist");
    let thead = $("<thead>").addClass("thead-light");
    let tr = $("<tr>");
    let el = $("<th>").attr("scope", "col").text("#");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Nome");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Cognome");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Codice Fiscale");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("e-mail");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("numero");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Data");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Fase");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Motivo");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Creata");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Creata da");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Aggiornata");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("Aggiornata da");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("");
    tr.append(el);
    el = $("<th>").attr("scope", "col").text("");
    tr.append(el);
    thead.append(tr);
    table.append(thead);
    
    let tbody = $("<tbody>");
    requests.forEach(element => {
        tr = $("<tr>");
        el = $("<th>").attr({"scope":"row","id":element.id}).text(element.id);
        tr.append(el);
        el = $("<td>").text(element.nome);
        tr.append(el);
        el = $("<td>").text(element.cognome);
        tr.append(el);
        el = $("<td>").text(element.codiceFiscale);
        tr.append(el);
        el = $("<td>").text(element.email);
        tr.append(el);
        el = $("<td>").text(element.numero);
        tr.append(el);
        el = $("<td>").text(element.dataRic);
        tr.append(el);
        el = $("<td>").text(element.fase);
        tr.append(el);
        el = $("<td>").text(element.motivo);
        tr.append(el);
        el = $("<td>").text(element.Created);
        tr.append(el);
        el = $("<td>").text(element.CreatedByNomeCognome);
        tr.append(el);
        el = $("<td>").text(element.lastUpdate);
        tr.append(el);
        el = $("<td>").text(element.lastUpdateByNomeCognome);
        tr.append(el);
        el = $("<td>").text("E");
        tr.append(el);
        el = $("<td>").text("D");
        tr.append(el);
        tbody.append(tr);
    });
    table.append(tbody);
    $("#main").append(table);
}

